name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Dependencies
        run: npm install

      - name: Run Cypress       
        run: npm run test      

      - name: Generate Report
        run: node cucumber-html-report.js
        
      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: cypress/reports
