name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Dependencies
        run: npm install

      - name: Run Cypress       
        run: npm run test      

      - name: Generate Report
        run: node cucumber-html-report.js
        
      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: reports-artifact
          path: |
            cypress/reports
            cypress/videos
            
      - name: Slack Notification
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
         args: '{\"channel\":\"C1234567890\",\"text\":\"Hello world\"}'
